#ifndef GOALKEEPER_DEFINES_H
#define GOALKEEPER_DEFINES_H

#define TIMEOUT_FOR_BALL_IN_BUFFER (1.5*1000*1000)
#define GOALKEEPER_ITERATION_TIME (35*1000)

#define GOALKEEPER_POSITION_X 	(0)
#define GOALKEEPER_POSITION_Y 	(40)

// GOALKEEPER BALL_DANGER_ZONE
#define BALL_IN_DANGER_ZONE_X 		(80)
#define BALL_IN_DANGER_ZONE_Y 		(125)
#define MAX_Y_TO_SEND_THE_BALL_AWAY (170)
#define MAX_Y_DIFF_FROM_BALL_TO_RETURN_TO_GOAL (150)
#define FAR_BALL_DISTANCE 	  		(170)

// GOALKEEPER_JUMP
#define FAR_RIGHT_GOAL_THRESHOLD	(90)
#define FAR_LEFT_GOAL_THRESHOLD 	(-90)
#define MIDDLE_RIGHT_GOAL_THRESHOLD (10)
#define MIDDLE_LEFT_GOAL_THRESHOLD 	(-10)

#define MIN_NUM_OF_BALLS_TO_STATIC_BALL_DECISION (7)
#define NUM_OF_BALLS_TO_DECIDE_JUMP				 (5)
#define EPSILON_BALL_MOVEMENT_STD				 (5)

// GOALKEEPER_TURN_TO_MIDDLE
#define MAX_TURN_COUNT_TO_MIDDLE_FOR_LEFT_JUMP	 (100)
#define MAX_TURN_COUNT_TO_MIDDLE_FOR_RIGHT_JUMP	 (130)
#define MIN_TIME_FOR_TURNING					 (1000 * 1000)
#define MAX_ANGLE_FOR_GOALKEEPER_POSITION		 (15)

// GOALKEEPER POSITION_YOURSELF, GO_BACK_TO_GOAL_CENTER
#define MAX_X_FOR_GOALKEEPER_POSITION_GOAL_TRACK 	(40)
#define MAX_Y_FOR_GOALKEEPER_POSITION_GOAL_TRACK 	(100)

#define MIN_CORRECT_ANGLE_COUNTER_FOR_RIGHT_ANGLE 	(7)

// GOALKEEPER STEP
#define MAX_X_FOR_GOALKEEPER_STEP				 	(30)
#define NUM_OF_BALLS_TO_DECIDE_RECENT_BALL_STATIC 	(3)
#define NUM_OF_BALLS_TO_DECIDE_STEP				 	(3)

#define MAX_X_DIFF_FROM_BALL 					(35)
#define MAX_ANGLE_FOR_STEP_ASIDE_CLOSE_DISTANCE (20)
#define MAX_ANGLE_FOR_STEP_ASIDE_FAR_DISTANCE 	(10)

// GOALKEEPER SHOULD I GO TO BALL
#define GOALKEEPER_SHOULD_I_GO_TO_BALL_DISTANC_OFFSET (30)

#endif
