#ifndef COLORSVALUES_H_
#define COLORSVALUES_H_

#define DEFAULT_ORANGE_MIN_HUE	0
#define DEFAULT_ORANGE_MAX_HUE	22
#define DEFAULT_ORANGE_MIN_SAT	60
#define DEFAULT_ORANGE_MIN_VAL	0

#define DEFAULT_YELLOW_MIN_HUE	23
#define DEFAULT_YELLOW_MAX_HUE	42// 49
#define DEFAULT_YELLOW_MIN_SAT	160//100//60
#define DEFAULT_YELLOW_MIN_VAL	0

#define DEFAULT_BLUE_MINUS_RED_THRESHOLD 10
#define DEFAULT_BLUE_MINUS_GREEN_THRESHOLD 10

#define DEFAULT_GREEN_MINUS_RED_THRESHOLD 30
#define DEFAULT_GREEN_MINUS_BLUE_THRESHOLD 20

//#define BLUE_MIN_HUE	100
//#define BLUE_MAX_HUE	125
#define BLUE_MIN_HUE	120
#define BLUE_MAX_HUE	120

#define BLUE_MIN_SAT	85

//#define GREEN_MIN_HUE	50
//#define GREEN_MAX_HUE	95

#define GREEN_MIN_HUE	60
#define GREEN_MAX_HUE	60
#define GREEN_MIN_SAT	30

#define YELLOW_AVG_HUE	30
#define GREEN_AVG_HUE	60
#define BLUE_AVG_HUE	120
#define ORANGE_AVG_HUE	19

#define BLACK_HUE		0
#define DEFAULT_BLACK_MAX_VAL	13

#define DEFAULT_WHITE_MAX_SAT	30
#define DEFAULT_WHITE_MIN_VAL	100

#define OTHER_HUE 85

#define MIN_SAT			0
#define MAX_SAT			255

#define MIN_VAL			0
#define MAX_VAL			255

#endif /* COLORSVALUES_H_ */
